server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: seismic-platform-backend
  
  datasource:
    url: jdbc:h2:mem:seismic_platform;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true
  
  security:
    jwt:
      secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
      expiration: 86400000 # 24 hours
      refresh-expiration: 604800000 # 7 days
  
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  
  websocket:
    allowed-origins: "http://localhost:4200"

logging:
  level:
    com.seismic: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Custom application properties
app:
  cors:
    allowed-origins: "http://localhost:4200,http://localhost:3000"
  notification:
    whatsapp:
      api-url: ${WHATSAPP_API_URL:}
      token: ${WHATSAPP_TOKEN:}
  mapbox:
    access-token: ${MAPBOX_ACCESS_TOKEN:}
